/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function parseCss(css: string): string
export interface AstBuffer {
  metadata: Int32Array
  bigString: string
}
export declare function parseCssToBuffer(css: string): AstBuffer
